### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by BDeveau** [PolicyStat/ckeditor-plugin-structured-headings#21]
- [x] re-apply style when changing level
- [x] change colon to period
- [x] Add margin around style dialog elements
- [x] Make style names more friendly
- [x] Remove Style Dropdown from Toolbar in Sample, with documentation on how to do so
- [x] On Style Dialog, add name label below the thumbnail
- [x] Default style not highlighted at start

**Comment by BDeveau** [comment]
![stylelabels](https://cloud.githubusercontent.com/assets/14978384/21618127/64a97e0c-d1b7-11e6-8acc-fd1cb99ea1b2.png)

**Comment by jms21852** [comment]
@BDeveau Could we put a touch of padding (5 pixels or so) above the labels? And, if possible, reduce the height of the modal: there is a lot of empty space above the buttons. 

Also, here is a first pass at naming them (line breaks intended):

Numeric

Numeric and
letters

Letters and
roman numeric

Roman numeric
and letters

**Comment by BDeveau** [comment]
I was fussing with padding for a while, I didn't like how if there are enough styles to generate a second row, that second row was a little too close to the top. So sure I'll toss in some padding and I'll test out those new, longer names. I'm not sure if spaces in the name are going to be kosher. I might need to implement a "description" to go with a name.

**Comment by BDeveau** [comment]
### Header Dropdown Removed
![image](https://cloud.githubusercontent.com/assets/14978384/21645875/d6b14fac-d261-11e6-8f20-978e24975cb9.png)

**Comment by BDeveau** [comment]
I renamed the default styles according to their per-level style, the spacing creating line breaks in the dialog. I also included an image with what it looks like with 5+ creating a second row, and how a style looks when no image is specified. (the text in the middle is the name itself)

### Default With Detailed Names
![image](https://cloud.githubusercontent.com/assets/14978384/21649326/476cd18c-d26f-11e6-8f28-06da4d77869a.png)
### 2 Rows, Style without Image
![image](https://cloud.githubusercontent.com/assets/14978384/21649288/282395ae-d26f-11e6-88ea-693bd9ede0e3.png)

**Comment by jms21852** [comment]
@BDeveau Curious: under what circumstances would the style w/o image thumbnail show up in the style selection modal?

**Comment by BDeveau** [comment]
@janasoroczak  "Style w/o Image" is the name of the style It's not actually a thumbnail image, I have this set up (for future purposes?) so that a dev can create new styles by changing configuration without needing to modify this plugin. If a style is created but no image is supplied for it, that is how it will currently appear. (thumbnail images are treated as optional)

**Comment by jms21852** [comment]
@BDeveau Gotcha! Everything looks good.

**Comment by caffodian** [comment]
If we do decide to play with indents, (we have decided not to, at least initially) http://stackoverflow.com/questions/13359776/indent-all-tags-following-h2-until-next-h2-is-hit-using-css might be useful.  linking here so I don't have to re-find it if we change our mind.
