### ISSUE TITLE
Implement the "toggle autonumbering" command

### ISSUE THREAD

**Issue by caffodian** [PolicyStat/ckeditor-plugin-structured-headings#3]
# what it does

It should add or remove the relevant autonumbering classes from a heading, if you are within a heading.  For now, since we don't want to fuss about CSS, we can just have it apply an "autonumber" class to the heading.  

# states

- “On” When the start of your current selection is in a heading block, the button should be “on”. It should have a dark background, similar to the behavior of the bulleted list button when your cursor is in a bulleted list) when your selection is in a heading block.
- “Off” When your current selection is in a paragraph block, the button should be “off”. This is the normal style.
- “Disabled” When your current selection is in anything else, the button should be “disabled”. The button text should be a light grey, similar to the behavior of the outdent button when your selection isn’t in a list.

# where to start 

- without getting too far into figuring out the guts of CSS (reserved for #2)
- create the command definition
- create a helper function to determine if a given heading element is autonumbered
- create a handler that fires on selection change.  This handler will check if:
    - you are in a heading
    - the heading is autonumbered
   and set the command state accordingly.

**Comment by caffodian** [comment]
We don't need to actually worry about the actual toolbar button for this - we can assert on the command status instead

**Comment by caffodian** [comment]
Good tests for these would be something like:

- set the editor html selection to have an already autonumbered heading.  check the command state is on
- set the selection to be in a non autonumbered heading.  check the command state is off
- set the selection to be in a paragraph - check the command state is disabled

and variants which involve moving the selection from elsewhere, into the 3 states above (instead of just starting the selection inside)

**Comment by BDeveau** [comment]
Things I'd like to see / implement next
- [ ] A button to toggle autonumber for an individual item (heading, image, table, whatever)
- [ ] A button to display a settings dialog, allowing user to select formatting options

**Comment by winhamwr** [comment]
> heading, image, table, whatever

Only headings should be numberable.

> allowing user to select formatting options

We don't want user-customization for most options. We want that done via configuration that the developer defines. 

We are going to need to allow the user to switch between numbering styles eventually, but we want to default to 1, 1.1, 1.1.1, 1.1.1.1 etc.  That's the most-desired style.

**Comment by BDeveau** [comment]
Selecting formatting from pre-defined options is what I was thinking about, not user-customizeable, users cant be trusted with something like that

**Comment by caffodian** [comment]
http://www.2ality.com/2012/01/numbering-headingshtml.html is a better writeup than the MDN article.

**Comment by caffodian** [comment]
And because I was curious about testing.  I wasn't sure if pseudo elements showed up in getComputedStyle, but apparently you can pass it in as a second parameter.  This might be useful for assertions on what the expected numbering is for a given heading, after executing the command.  

 https://davidwalsh.name/pseudo-element 
https://developer.mozilla.org/en/docs/Web/API/Window/getComputedStyle#Use_with_pseudo-elements
