### ISSUE TITLE
Label fixes (again) 

### ISSUE THREAD

**Issue by caffodian** [PolicyStat/ckeditor-plugin-structured-headings#69]
## usability test

- [x] The default state for the formatting dropdown is “format”. It should say “Formatting”
- [x] The tooltip on rollover of the format dropdown says “Numbering Formats”. It should say “Text Formatting”

## some reverts 

- [x] "Styling" => "Numbering"
- [x] "Clear Styling" => "Clear Numbering"
- [x] "Restart Styling" => "Restart Numbering"

## Heading labels (update the dropdown label and also the background image displayed in the editor):
- [x] Heading 2 => Part Heading
- [x] Heading 3 => Subpart Heading
- [x] Heading 4 => Section Heading
- [x] Heading 5 => Subsection Heading
- [ ] Heading 6 => Remove this from dropdown but all existing H6s to continue to exist

## Other UI Changes

Include button for "Highlight"

**Comment by caffodian** [comment]
H6 removal will be done pstat side through config.  same with highlight

**Comment by bocribbz** [comment]
Maybe striketrough H6 and highlight in the issue description.

**Comment by caffodian** [comment]
fixed in #70
